#!/usr/bin/with-contenv bash

printf '[cont-init.d] Setting structure\n'

chmod +x /deemix-server

printf '[cont-init.d] Creating abc user\n'

adduser --disabled-password --uid 0 --ingroup root abc

printf '[cont-init.d] Setting downloads folder\n'

mkdir -p /share/Freebox/Musiques
ln -s /share/Freebox/Musiques /downloads

# if [ ! -z ${DISABLE_OWNERSHIP_CHECK} ]; then
#     printf '[cont-init.d] Download Folder Ownership Check disabled by Environment Variable\n'
# else
#     printf '[cont-init.d] Fixing Folder Permissions - Downloads Folder\n'
# 	  find /downloads -type d -exec chown abc:abc {} +
# fi

printf '[cont-init.d] Setting config folder\n'

mkdir -p /homeassistant/deemix
# chown -R abc:abc /homeassistant/deemix
ln -s /homeassistant/deemix /config

if [ -f "/deemix/config.json" ]; then
    cp /deemix/config.json /config/config.json
    # chown abc:abc /config/config.json
    rm /deemix/config.json
fi

# Fix misconfigured download locations. The container's download map is always /downloads.
if [ -f "/config/config.json" ]; then
    jq '.downloadLocation = "/downloads"' /config/config.json > tmp.$$.json && mv tmp.$$.json /config/config.json
    chown abc:abc /config/config.json
fi

